---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Naming/FileName:
  Exclude:
    - lib/tmux-erb-parser.rb
Metrics/BlockLength:
  Exclude:
    - test/**/*
