name: Run TestUnit

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 0:00 UTC on every sunday

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}${{ (matrix.options && ' w/ JIT') || '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
        options:
          - ""
          - --jit
        exclude:
          - ruby-version: 2.5
            options: --jit
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: 518a2565046a8d3d996e3e6fc49eba88bb15cac99c883f83e5dbd8d3a3089bdd
      with:
        coverageCommand: bundle exec rake
